# Generated by Django 5.0.4 on 2024-11-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
